[versions]
kotlin = "2.2.10"
kotest = "6.0.0"

[libraries]

gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.23.8" }
gradle-plugin-ktlint = { module = "org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin", version = "5.0.0" }
gradle-plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.0.0" }
gradle-plugin-maven-central-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.34.0" }

swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version = "2.1.32" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.13.4" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.13" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }

[plugins]

plugin-publish = { id = "com.gradle.plugin-publish", version = "1.3.1" }

buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.6.7" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
