[versions]
kotlin = "2.2.21"
kotest = "6.0.3"
ktor = "3.3.2"

[libraries]

gradle-plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-plugin-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version = "1.23.8" }
gradle-plugin-ktlint = { module = "org.jmailen.kotlinter:org.jmailen.kotlinter.gradle.plugin", version = "5.0.0" }
gradle-plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "2.1.0" }
gradle-plugin-maven-central-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.34.0" }

kotlin-gradle-plugin-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }

swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version = "2.1.35" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version = "5.13.4" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.13" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version = "2.0.17" }
kotlinx-dateime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.2" }

ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-di = { module = "io.ktor:ktor-server-di", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

[plugins]

plugin-publish = { id = "com.gradle.plugin-publish", version = "2.0.0" }

buildconfig = { id = "com.github.gmazzo.buildconfig", version = "5.7.1" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
openapi = { id = "org.openapi.generator", version = "7.15.0" }

[bundles]
ktor = ["ktor-server-content-negotiation", "ktor-server-core", "ktor-serialization-kotlinx-json", "ktor-server-auth", "ktor-server-cio", "ktor-server-config-yaml", "ktor-server-di"]
